# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-12-01 16:13
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(default=2017, help_text='Année pendant laquelle est passée le concours. Par exemple en 2016-2017 mettre : 2017', validators=[django.core.validators.MaxValueValidator(2042), django.core.validators.MinValueValidator(2005)], verbose_name='Année')),
                ('tex_preambule', models.TextField(blank=True, verbose_name='Préambule LaTeX personnalisé')),
                ('option', models.CharField(choices=[('A', 'Option A : Probabilités et statistiques'), ('B', 'Option B : Calcul scientifique'), ('C', 'Option C : Algèbre et calcul formel'), ('D', 'Option D : Modélisation et analyse de système informatique')], max_length=1, verbose_name='Option du concours')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'profil agrégatif',
                'verbose_name_plural': 'profils agrégatifs',
            },
        ),
    ]
