# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-07 23:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oral', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='effectivedevelopment',
            name='remarks',
            field=models.TextField(blank=True, verbose_name='Remarques personnelles concernant le développement.'),
        ),
    ]
